# Generated by Django 5.2.3 on 2025-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='reminder_sent',
            new_name='hr24_reminder_sent',
        ),
        migrations.AddField(
            model_name='appointment',
            name='hr4_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
