# Generated by Django 5.2.3 on 2025-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0004_rename_reminder_sent_appointment_hr24_reminder_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
